name:  avl_tree
description: >
   An implementation of an AVL tree (a balanced binary search tree)

authors: 
  - Stefano Furin<furins@gmail.com>
  - Karl Guggisberg <karl.guggisberg@guggis.ch>
  - stewbasic <https://github.com/stewbasic>

environment:
  sdk: ">=2.1.0 <3.0.0"

version: 0.2.2
homepage: https://github.com/furins/dart-avl-tree.git
documentation: http://gubaer.github.io/dart-avl-tree/

dev_dependencies:
  test: any